### ISSUE TITLE
(node:824760) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by propjk007** [enuchi/React-Google-Apps-Script#23]
Ran `npm run deploy`, however, the process failed during `clasp push`. Please see the terminal readout below. 

Note: `npm run build` then `cd dist` and `clasp push` was successful.

#### Versions:
```
npm 6.13.0
npx 10.2.0
clasp 2.3.0
```

```bash
(env) C:\repos\React-Google-Apps-Script>npm run deploy

> react-google-apps-script@1.0.0 deploy C:\repos\React-Google-Apps-Script
> npm run build && npx clasp push


> react-google-apps-script@1.0.0 build C:\repos\React-Google-Apps-Script
> webpack --mode production

clean-webpack-plugin: C:\repos\React-Google-Apps-Script\dist has been removed.
info: WebpackClean - removed C:\repos\React-Google-Apps-Script\dist\main.js
info: WebpackClean - DONE
Hash: 8275ad7f3cbb95ed67b597f8d734ad1bb48e9ad5a8394b4d67e47bdd7fbd8d3d07ff36c0eb366916
Version: webpack 4.35.3
Child COPY APPSSCRIPT.JSON:
    Hash: 8275ad7f3cbb95ed67b5
    Time: 917ms
    Built at: 11/17/2019 10:04:08 AM
              Asset       Size  Chunks             Chunk Names
    appsscript.json  204 bytes          [emitted]
            main.js   1.09 KiB       0  [emitted]  main
    Entrypoint main = main.js
    [0] ./appsscript.json 204 bytes {0} [built]
Child CLIENT - main dialog:
    Hash: 97f8d734ad1bb48e9ad5
    Time: 9723ms
    Built at: 11/17/2019 10:04:17 AM
        Asset     Size  Chunks                    Chunk Names
    main.html  252 KiB          [emitted]  [big]
      main.js  252 KiB       0  [emitted]  [big]  main
    Entrypoint main [big] = main.js
     [7] ./src/client/styles.css 1.06 KiB {0} [built]
    [13] (webpack)/buildin/global.js 472 bytes {0} [built]
    [27] ./node_modules/css-loader!./src/client/styles.css 1.9 KiB {0} [built]
    [31] ./src/client/main.jsx + 4 modules 3.67 KiB {0} [built]
         | ./src/client/main.jsx 204 bytes [built]
         | ./src/client/server.js 636 bytes [built]
         |     + 3 hidden modules
        + 28 hidden modules

    WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
    This can impact web performance.
    Assets: 
      main.js (252 KiB)
      main.html (252 KiB)

    WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
    Entrypoints:
      main (252 KiB)
          main.js
    

    WARNING in webpack performance recommendations: 
    You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
    For more info visit https://webpack.js.org/guides/code-splitting/
    Child html-webpack-plugin for "main.html":
         1 asset
        Entrypoint undefined = main.html
        [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/client/dialog-template.html 412 bytes {0} [built]
        [2] (webpack)/buildin/global.js 472 bytes {0} [built]
        [3] (webpack)/buildin/module.js 497 bytes {0} [built]
            + 1 hidden module
Child CLIENT - about sidebar:
    Hash: a8394b4d67e47bdd7fbd
    Time: 6703ms
    Built at: 11/17/2019 10:04:14 AM
         Asset     Size  Chunks             Chunk Names
    about.html  218 KiB          [emitted]
       main.js  218 KiB       0  [emitted]  main
    Entrypoint main = main.js
     [7] (webpack)/buildin/global.js 472 bytes {0} [built]
     [8] ./src/client/styles.css 1.06 KiB {0} [built]
     [9] ./node_modules/css-loader!./src/client/styles.css 1.9 KiB {0} [built]
    [13] ./src/client/about.jsx + 1 modules 640 bytes {0} [built]
         | ./src/client/about.jsx 205 bytes [built]
         |     + 1 hidden module
        + 10 hidden modules
    Child html-webpack-plugin for "about.html":
         1 asset
        Entrypoint undefined = about.html
        [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/client/dialog-template.html 412 bytes {0} [built]
        [2] (webpack)/buildin/global.js 472 bytes {0} [built]
        [3] (webpack)/buildin/module.js 497 bytes {0} [built]
            + 1 hidden module
Child SERVER:
    Hash: 8d3d07ff36c0eb366916
    Time: 1836ms
    Built at: 11/17/2019 10:04:09 AM
      Asset     Size  Chunks             Chunk Names
    code.js  5.6 KiB       0  [emitted]  main
    Entrypoint main = code.js
    [0] ./src/server/sheets-utilities.js 1.67 KiB {0} [built]
    [1] ./src/server/code.js 437 bytes {0} [built]
    [2] (webpack)/buildin/global.js 472 bytes {0} [built]
info: WebpackClean - removed C:\repos\React-Google-Apps-Script\dist\main.js
info: WebpackClean - DONE
(node:824760) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
? Manifest file has been updated. Do you want to push and overwrite? Yes
Push failed. Errors:
(node:824760) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at C:\repos\React-Google-Apps-Script\node_modules\@google\clasp\src\files.js:350:50
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:824760) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch bl
ock, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:824760) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the N
ode.js process with a non-zero exit code.
```

**Comment by enuchi** [comment]
Hm. You should need to `cd dist`. All commands should be run from root.

Does it work if you do the following?
1. `npm run build`
2. `npx clasp push`

**Comment by propjk007** [comment]
Yes, I run the following command and it works fine:
```npm run build && cd dist && clasp push && cd ..```

**Comment by propjk007** [comment]
No, following #1 then #2 did not work.

**Comment by enuchi** [comment]
did you modify the source code at all?

**Comment by enuchi** [comment]
Please reopen if you still have trouble with this.

**Comment by karthikshetty03** [comment]
(node:16293) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
